openapi: 3.0.1
info:
  title: Sample API
  description: API description in Markdown.
  version: 1.0.0
servers:
- url: https://api.example.com/v1
paths:
  /users:
    get:
      summary: Returns a list of users.
      description: Optional extended description in Markdown.
      operationId: users_get
      responses:
        "200":
          description: OK
          content: {}
      x-openapi-router-controller: swagger_server.controllers.default_controller
components:
  schemas: {}
x-original-swagger-version: "2.0"

